### ISSUE TITLE
Add a duplicate monster for Custom Skill mode in Cherry Doom

### ISSUE THREAD

**Issue by PorpiangWriter** [xemonix0/Cherry-Doom#9]
![Screenshot 2024-10-31 154826](https://github.com/user-attachments/assets/09584129-130f-47ee-8f2f-d35d11a9275b)
Nugget Doom already has it in version 3.3.0, so can you add this parameter to Cherry Doom's custom skill?

**Comment by xemonix0** [comment]
I'll merge all changes from Nugget Doom 3.3.0 into Cherry Doom soon (hopefully), sorry for the delay

**Comment by xemonix0** [comment]
Merged changes from Nugget Doom 3.3.0 in 546e09d0b330911c688999bad0a012b9bf8ff1b4.

**Comment by PorpiangWriter** [comment]
Thanks, however, Nugget Doom 4.0.0 was already released, there are new features in that version to be included in the next version of Cherry Doom. https://github.com/MrAlaux/Nugget-Doom/releases/tag/nugget-doom-4.0.0

**Comment by xemonix0** [comment]
Yes, I am aware. It was released just this morning. I will be merging it into the `master` branch soon.

**Comment by PorpiangWriter** [comment]
I don't know if you're aware of this, but I need to remind you that Nugget Doom 4.1.0 was released. https://github.com/MrAlaux/Nugget-Doom/releases/tag/nugget-doom-4.1.0

**Comment by xemonix0** [comment]
Thanks, changes from 4.1.0 have just been merged into the `master` branch, apologies for the delay! Also, just want to let you know, I actively follow Nugget Doom and am aware of new releases as they happen, so you don't need to remind me about them.
